#https://pulsar.apache.org/docs/4.0.x/helm-deploy/
#https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml

volumes:
  persistence: true
  local_storage: false

affinity:
  anti_affinity: false

components:
  oxia: false # replace zookeeper
  zookeeper: true
  bookkeeper: true
  autorecovery: true 
  broker: true
  # This one causes helm not to complete but is not needed as can connect directly to broker
  proxy: false 
  toolset: false
  pulsar_manager: true

kube-prometheus-stack:
  enabled: true
  prometheusOperator:
    enabled: true
  grafana:
    enabled: true
  alertmanager:
    enabled: false
  prometheus:
    enabled: true

zookeeper:
  replicaCount: 1
  volumes:
    data:
      name: data
      size: 2Gi #20
      local_storage: false

bookkeeper:
  replicaCount: 1
  volumes:
    journal:
      size: 2Gi #10
      local_storage: false
    ledger:
      size: 2Gi #50
      local_storage: false
  configData:
    # minimal memory use for bookkeeper
    # https://bookkeeper.apache.org/docs/reference/config#db-ledger-storage-settings
    dbStorage_writeCacheMaxSizeMb: "32"
    dbStorage_readAheadCacheMaxSizeMb: "32"
    dbStorage_rocksDB_writeBufferSizeMB: "8"
    dbStorage_rocksDB_blockCacheSize: "8388608"

broker:
  replicaCount: 1
  configData:
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"

proxy:
  replicaCount: 1
