#https://pulsar.apache.org/docs/4.0.x/helm-deploy/
#https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/values.yaml

volumes:
  persistence: true

affinity:
  anti_affinity: false

components:
  zookeeper: true
  bookkeeper: true
  autorecovery: true
  broker: true
  proxy: true
  toolset: true # toto:turn off

kube-prometheus-stack:
  enabled: true
  prometheus:
    replicas: 1
  grafana:
    replicas: 1

zookeeper:
  replicaCount: 1

bookkeeper:
  replicaCount: 1

broker:
  replicaCount: 1

proxy:
  replicaCount: 1

#pulsar_manager:
#  configData:
#    ENV_SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
#    SPRING_CONFIGURATION_FILE: "/pulsar-manager/pulsar-manager/application.properties"
#    PULSAR_MANAGER_OPTS: " -Dlog4j2.formatMsgNoLookups=true"